'use client'

import { useEffect, useMemo, useState } from 'react'
import { ArrowRight, Check, ChevronDown, CircleHelp, Clock3, LockKeyhole, Menu, Moon, Minus, Plus, Search, ShoppingBag, Sun, Ticket, Utensils, X } from 'lucide-react'

type Session = 'Breakfast' | 'Lunch' | 'Supper'
type MealType = 'Student Meals' | 'Premium Dining'
type Meal = { id: string; name: string; description: string; price: number; category: string; type: MealType; sessions: Session[]; image: string; available: boolean; stock?: number }
type CartItem = Meal & { quantity: number }
type Order = { code: string; name: string; phone: string; total: number; status: 'Paid' | 'Ready' | 'Served'; items: CartItem[]; createdAt: string }

const meals: Meal[] = [
  { id: 'tea', name: 'Tea', description: 'Kenyan tea served hot', price: 20, category: 'Breakfast', type: 'Student Meals', sessions: ['Breakfast'], image: 'https://images.unsplash.com/photo-1544787219-7f47ccb76574?auto=format&fit=crop&w=900&q=85', available: true },
  { id: 'mandazi', name: 'Mandazi', description: 'Fresh campus breakfast pastry', price: 20, category: 'Breakfast', type: 'Student Meals', sessions: ['Breakfast'], image: 'https://images.unsplash.com/photo-1623238913973-21e45cced554?auto=format&fit=crop&w=900&q=85', available: true },
  { id: 'bread', name: 'Bread', description: 'Sliced bread for a quick breakfast', price: 30, category: 'Breakfast', type: 'Student Meals', sessions: ['Breakfast'], image: 'https://images.unsplash.com/photo-1509440159596-0249088772ff?auto=format&fit=crop&w=900&q=85', available: true },
  { id: 'rice-beans', name: 'Rice + Beans', description: 'Rice served with beans stew', price: 50, category: 'Plates', type: 'Student Meals', sessions: ['Lunch', 'Supper'], image: 'https://images.unsplash.com/photo-1555952333-3b6d3c7c9b3e?auto=format&fit=crop&w=900&q=85', available: true },
  { id: 'githeri', name: 'Githeri', description: 'Maize and beans, lightly seasoned', price: 50, category: 'Plates', type: 'Student Meals', sessions: ['Lunch', 'Supper'], image: 'https://images.unsplash.com/photo-1595503240812-728e4d6a1d6b?auto=format&fit=crop&w=900&q=85', available: true },
  { id: 'ugali', name: 'Ugali', description: 'Traditional maize meal portion', price: 30, category: 'Staples', type: 'Student Meals', sessions: ['Lunch', 'Supper'], image: 'https://images.unsplash.com/photo-1601050690597-df0568f70950?auto=format&fit=crop&w=900&q=85', available: true },
  { id: 'chapati-beans', name: 'Chapati + Beans', description: 'Soft chapati with beans stew', price: 70, category: 'Plates', type: 'Student Meals', sessions: ['Lunch', 'Supper'], image: 'https://images.unsplash.com/photo-1628294895950-9805252327bc?auto=format&fit=crop&w=900&q=85', available: true },
  { id: 'sukuma', name: 'Sukuma Wiki', description: 'Freshly cooked greens', price: 30, category: 'Sides', type: 'Student Meals', sessions: ['Lunch', 'Supper'], image: 'https://images.unsplash.com/photo-1540420773420-3366772f4999?auto=format&fit=crop&w=900&q=85', available: true },
  { id: 'beef', name: 'Beef Stew', description: 'Tender beef in rich tomato stew', price: 100, category: 'Sides', type: 'Student Meals', sessions: ['Lunch', 'Supper'], image: 'https://images.unsplash.com/photo-1603360946369-dc9bb6258143?auto=format&fit=crop&w=900&q=85', available: true },
  { id: 'pilau', name: 'Pilau', description: 'Fragrant spiced rice with beef', price: 150, category: 'Premium Dining', type: 'Premium Dining', sessions: ['Lunch', 'Supper'], image: 'https://images.unsplash.com/photo-1599043513900-ed6fe01d4d58?auto=format&fit=crop&w=900&q=85', available: true },
  { id: 'chicken-rice', name: 'Chicken + Rice', description: 'Chicken served with seasoned rice', price: 220, category: 'Premium Dining', type: 'Premium Dining', sessions: ['Lunch', 'Supper'], image: 'https://images.unsplash.com/photo-1532550907401-a500c9a57435?auto=format&fit=crop&w=900&q=85', available: true },
  { id: 'fish-ugali', name: 'Fish + Ugali', description: 'Fish served with ugali', price: 250, category: 'Premium Dining', type: 'Premium Dining', sessions: ['Lunch', 'Supper'], image: 'https://images.unsplash.com/photo-1519708227418-c8fd9a32b7a2?auto=format&fit=crop&w=900&q=85', available: true },
  { id: 'soda', name: 'Soda', description: 'Cold soft drink', price: 60, category: 'Drinks', type: 'Student Meals', sessions: ['Lunch', 'Supper'], image: 'https://images.unsplash.com/photo-1581006852262-e4307cf6283a?auto=format&fit=crop&w=900&q=85', available: true },
]

const sessionOrder: Session[] = ['Breakfast', 'Lunch', 'Supper']
const money = (value: number) => `KES ${value.toLocaleString()}`

export default function Home() {
  const [view, setView] = useState<'home' | 'menu' | 'track' | 'management'>('home')
  const [session, setSession] = useState<Session>('Lunch')
  const [mealType, setMealType] = useState<MealType>('Student Meals')
  const [category, setCategory] = useState('All')
  const [query, setQuery] = useState('')
  const [cart, setCart] = useState<CartItem[]>([])
  const [order, setOrder] = useState<Order | null>(null)
  const [checkoutOpen, setCheckoutOpen] = useState(false)
  const [dark, setDark] = useState(false)
  const [mobileNav, setMobileNav] = useState(false)
  const [trackCode, setTrackCode] = useState('')
  const [lookupMessage, setLookupMessage] = useState('')
  const [name, setName] = useState('')
  const [phone, setPhone] = useState('')
  const [paymentPending, setPaymentPending] = useState(false)
  const [served, setServed] = useState(false)
  const [managementUnlocked, setManagementUnlocked] = useState(false)
  const [adminOpen, setAdminOpen] = useState(false)
  const [adminUser, setAdminUser] = useState('')
  const [adminPass, setAdminPass] = useState('')
  const [adminError, setAdminError] = useState('')
  const [unavailableIds, setUnavailableIds] = useState<string[]>([])

  useEffect(() => {
    const saved = window.localStorage.getItem('must-cafeteria-state')
    if (saved) try { const state = JSON.parse(saved); setCart(state.cart ?? []); setOrder(state.order ?? null); setDark(state.dark ?? false); setUnavailableIds(state.unavailableIds ?? []); setManagementUnlocked(state.managementUnlocked ?? false) } catch { window.localStorage.removeItem('must-cafeteria-state') }
  }, [])
  useEffect(() => { window.localStorage.setItem('must-cafeteria-state', JSON.stringify({ cart, order, dark, unavailableIds, managementUnlocked })) }, [cart, order, dark, unavailableIds, managementUnlocked])

  const availableForSession = meals.filter((meal) => meal.type === mealType && meal.sessions.includes(session))
  const categories = ['All', ...Array.from(new Set(availableForSession.map((meal) => meal.category)))]
  const filteredMeals = useMemo(() => availableForSession.filter((meal) => (category === 'All' || meal.category === category) && `${meal.name} ${meal.description}`.toLowerCase().includes(query.toLowerCase())), [availableForSession, category, query])
  const isAvailable = (meal: Meal) => meal.available && !unavailableIds.includes(meal.id)
  const count = cart.reduce((sum, item) => sum + item.quantity, 0)
  const total = cart.reduce((sum, item) => sum + item.price * item.quantity, 0)

  function changeSession(next: Session) { setSession(next); setCategory('All'); setQuery(''); setView('menu') }
  function add(meal: Meal) { if (!isAvailable(meal)) return; setCart((items) => items.some((item) => item.id === meal.id) ? items.map((item) => item.id === meal.id ? { ...item, quantity: Math.min(item.quantity + 1, 10) } : item) : [...items, { ...meal, quantity: 1 }]) }
  function change(id: string, delta: number) { setCart((items) => items.map((item) => item.id === id ? { ...item, quantity: Math.max(0, Math.min(item.quantity + delta, 10)) } : item).filter((item) => item.quantity > 0)) }
  function placeOrder() { if (!name.trim() || phone.replace(/\D/g, '').length < 9 || !cart.length || paymentPending) return; setPaymentPending(true); window.setTimeout(() => { const next: Order = { code: `MUST-${Math.floor(1000 + Math.random() * 9000)}`, name: name.trim(), phone, total, status: 'Paid', items: cart, createdAt: new Date().toISOString() }; setOrder(next); setPaymentPending(false); setCheckoutOpen(false); setCart([]); setView('track'); setTrackCode(next.code); setLookupMessage('Payment received. Your order is confirmed.') }, 1200) }
  function loginManagement() { if (adminUser === 'manager@must.ac.ke' && adminPass === 'MUST2026!') { setManagementUnlocked(true); setAdminOpen(false); setAdminError(''); setView('management') } else setAdminError('Use the demo credentials shown below.') }
  function lookupOrder() { if (!trackCode.trim()) { setLookupMessage('Enter your order code to continue.'); return } if (!order || trackCode.trim().toUpperCase() !== order.code) { setLookupMessage('We couldn’t find an order with that code.'); return } setLookupMessage('Order found. Status is up to date.') }

  return <div className={dark ? 'app dark' : 'app'}>
    <header className="site-header"><div className="header-inner"><button className="brand" onClick={() => setView('home')} aria-label="MUST home"><img src="/must-icon.svg" alt="Meru University of Science and Technology logo" /></button><nav className={mobileNav ? 'main-nav open' : 'main-nav'} aria-label="Main navigation"><button className={view === 'home' ? 'active' : ''} onClick={() => { setView('home'); setMobileNav(false) }}>Home</button><button className={view === 'menu' ? 'active' : ''} onClick={() => { setView('menu'); setMobileNav(false) }}>Menu</button><button className={view === 'track' ? 'active' : ''} onClick={() => { setView('track'); setMobileNav(false) }}>Track order</button><button onClick={() => setMobileNav(false)}>Help</button><button className="management-link" onClick={() => managementUnlocked ? setView('management') : setAdminOpen(true)}>Management</button></nav><div className="header-actions"><button className="icon-button" onClick={() => setDark(!dark)} aria-label={dark ? 'Use light theme' : 'Use dark theme'}>{dark ? <Sun /> : <Moon />}</button><button className="cart-button" onClick={() => setCheckoutOpen(true)} aria-label={`Cart with ${count} items`}><ShoppingBag /><span>{count}</span></button><button className="menu-button" onClick={() => setMobileNav(!mobileNav)} aria-label="Open menu"><Menu /></button></div></div></header>

    <main>
      {view === 'home' && <><section className="service-hero"><div><p className="eyebrow">MERU UNIVERSITY OF SCIENCE AND TECHNOLOGY</p><h1>Order before you reach the counter.</h1><p className="hero-copy">Choose what is available for this meal session, pay with M-Pesa, and collect it faster.</p><div className="hero-actions"><button className="primary" onClick={() => setView('menu')}>Order lunch <ArrowRight /></button><button className="text-button" onClick={() => setView('track')}>Track an order</button></div></div><div className="service-note"><span className="live-dot" />M-Pesa payments · Live meal availability</div></section><section className="session-strip"><div><p className="eyebrow">TODAY&apos;S SERVICE</p><h2>Choose a meal session</h2></div><div className="session-tabs">{sessionOrder.map((item) => <button key={item} className={session === item ? 'selected' : ''} onClick={() => changeSession(item)}>{item}<span>{item === 'Lunch' ? 'Main service' : item === 'Breakfast' ? 'Morning service' : 'Evening service'}</span></button>)}</div></section></>}
      {(view === 'home' || view === 'menu') && <section className="menu-section"><div className="section-heading"><div><p className="eyebrow">{session.toUpperCase()} MENU</p><h2>{view === 'home' ? 'Available today' : 'Order your meal'}</h2></div><span className="menu-context"><Clock3 /> {session} · updated live</span></div><div className="menu-toolbar"><div className="segmented"><button className={mealType === 'Student Meals' ? 'selected' : ''} onClick={() => { setMealType('Student Meals'); setCategory('All') }}>Student Meals</button><button className={mealType === 'Premium Dining' ? 'selected' : ''} onClick={() => { setMealType('Premium Dining'); setCategory('All') }}>Premium Dining</button></div><label className="search-box"><Search /><input value={query} onChange={(e) => setQuery(e.target.value)} placeholder="What are you looking for?" aria-label="Search meals" /></label></div><div className="filter-row">{categories.map((item) => <button key={item} className={category === item ? 'filter active' : 'filter'} onClick={() => setCategory(item)}>{item}</button>)}</div><div className="meal-grid">{filteredMeals.map((meal) => <article className="meal-card" key={meal.id}><div className="meal-image"><img src={meal.image} alt={meal.name} loading="lazy" /><span className={isAvailable(meal) ? 'available' : 'sold-out'}>{isAvailable(meal) ? 'Available' : 'Sold out'}</span></div><div className="meal-info"><div><h3>{meal.name}</h3><p>{meal.description}</p></div><div className="meal-buy"><strong>{money(meal.price)}</strong><button className="add-button" disabled={!isAvailable(meal)} onClick={() => add(meal)}>{isAvailable(meal) ? <><Plus /> Add</> : 'Sold out'}</button></div></div></article>)}</div>{!filteredMeals.length && <div className="empty"><Search /><h3>No meals found.</h3><p>Try another session, category or search.</p></div>}</section>}
      {view === 'track' && <section className="page-section track-page"><p className="eyebrow">ORDER STATUS</p><h1>Track your order</h1><p className="lead">Enter your order code to see the latest update at the counter.</p><div className="track-form"><input value={trackCode} onChange={(e) => setTrackCode(e.target.value)} placeholder="e.g. MUST-4821" aria-label="Order code" /><button className="primary" onClick={lookupOrder}>Find order</button></div>{lookupMessage && <p className="form-message" role="status">{lookupMessage}</p>}{order && <div className="order-status"><div className="order-status-top"><div><span className="eyebrow">ORDER {order.code}</span><h2>{order.name}&apos;s order</h2></div><span className="status-pill">{served ? 'Served' : order.status}</span></div><div className="progress"><div className="progress-step done"><span><Check /></span><b>Order received</b><small>Order is in the queue</small></div><div className="progress-step done"><span><Check /></span><b>Payment confirmed</b><small>M-Pesa payment received</small></div><div className={served ? 'progress-step done' : 'progress-step'}><span>{served ? <Check /> : <Clock3 />}</span><b>{served ? 'Served' : 'Ready for pickup'}</b><small>{served ? 'Enjoy your meal' : 'Say your code at the counter'}</small></div></div><div className="pickup-note"><Ticket /> <span>Go to the cafeteria counter and say <strong>{order.code}</strong>.</span></div></div>}{!order && <div className="track-empty"><Ticket /><h3>Your order will appear here.</h3><p>After payment, use the code on your confirmation screen.</p></div>}</section>}
      {view === 'management' && <section className="page-section management-page"><div className="management-head"><div><p className="eyebrow">CAFETERIA OPERATIONS</p><h1>Serve students faster.</h1><p className="lead">Live queue · {session} · first come, first served</p></div><button className="outline-button" onClick={() => { setManagementUnlocked(false); setView('home') }}><LockKeyhole /> Sign out</button></div><div className="stats"><div><span>Active orders</span><strong>{served || !order ? 0 : 1}</strong></div><div><span>Today&apos;s revenue</span><strong>{money(order ? order.total : 0)}</strong></div><div><span>Served today</span><strong>{served ? 1 : 0}</strong></div></div><div className="queue"><div className="queue-heading"><div><p className="eyebrow">LIVE ORDER QUEUE</p><h2>Orders to serve</h2></div><span className="status-pill">Live</span></div>{order && !served ? <div className="queue-row"><div className="queue-number">#1</div><div className="queue-details"><strong>{order.code} · {order.name}</strong><span>{order.items.map((item) => `${item.quantity} × ${item.name}`).join(' · ')} · Paid just now</span></div><strong>{money(order.total)}</strong><button className="primary small" onClick={() => { setServed(true); setOrder({ ...order, status: 'Served' }) }}>Mark served</button></div> : <div className="queue-empty"><Check /><span>{served ? 'Order served. The queue is clear.' : 'No active orders right now.'}</span></div>}</div><div className="availability-panel"><div><p className="eyebrow">MENU AVAILABILITY</p><h2>Switch meals on or off</h2></div><div className="availability-list">{meals.filter((meal) => meal.sessions.includes(session)).slice(0, 8).map((meal) => <div className="availability-row" key={meal.id}><span><strong>{meal.name}</strong><small>{meal.sessions.join(' · ')}</small></span><button className={isAvailable(meal) ? 'toggle on' : 'toggle'} onClick={() => setUnavailableIds((ids) => ids.includes(meal.id) ? ids.filter((id) => id !== meal.id) : [...ids, meal.id])} aria-label={`Set ${meal.name} ${isAvailable(meal) ? 'unavailable' : 'available'}`}>{isAvailable(meal) ? 'Available' : 'Sold out'}</button></div>)}</div></div></section>}
    </main>

    {count > 0 && !checkoutOpen && <button className="sticky-cart" onClick={() => setCheckoutOpen(true)}><span><ShoppingBag /> {count} {count === 1 ? 'item' : 'items'}</span><strong>{money(total)} <ArrowRight /></strong></button>}
    {checkoutOpen && <div className="overlay" role="presentation" onClick={() => setCheckoutOpen(false)}><aside className="cart-drawer" role="dialog" aria-modal="true" aria-labelledby="cart-title" onClick={(e) => e.stopPropagation()}><div className="drawer-head"><div><p className="eyebrow">YOUR ORDER</p><h2 id="cart-title">Cart <span>({count})</span></h2></div><button className="icon-button" onClick={() => setCheckoutOpen(false)} aria-label="Close cart"><X /></button></div>{cart.length ? <><div className="cart-items">{cart.map((item) => <div className="cart-item" key={item.id}><img src={item.image} alt="" /><div><strong>{item.name}</strong><span>{money(item.price)} each</span><div className="quantity"><button onClick={() => change(item.id, -1)} aria-label={`Remove one ${item.name}`}><Minus /></button><b>{item.quantity}</b><button onClick={() => change(item.id, 1)} aria-label={`Add one ${item.name}`}><Plus /></button></div></div><strong>{money(item.price * item.quantity)}</strong></div>)}</div><div className="cart-total"><span>Total</span><strong>{money(total)}</strong></div><div className="checkout-form"><label>Full name<input value={name} onChange={(e) => setName(e.target.value)} placeholder="e.g. John Mwangi" /></label><label>Phone number<input value={phone} onChange={(e) => setPhone(e.target.value)} placeholder="07XX XXX XXX" inputMode="tel" /></label><div className="payment-choice"><span><span className="payment-mark">M</span><span><strong>M-Pesa</strong><small>STK Push payment</small></span></span><span className="active-payment">Active</span></div><div className="payment-choice disabled-payment"><span><span className="payment-mark wallet">W</span><span><strong>E-wallet</strong><small>Campus wallet</small></span></span><span>Coming soon</span></div><button className="primary pay-button" disabled={!name.trim() || phone.replace(/\D/g, '').length < 9 || paymentPending} onClick={placeOrder}>{paymentPending ? 'Requesting M-Pesa payment…' : <>Pay {money(total)} with M-Pesa <ArrowRight /></>}</button><small className="secure-note">You will receive an M-Pesa prompt on your phone.</small></div></> : <div className="cart-empty"><ShoppingBag /><h3>Your cart is empty</h3><p>Add a meal from the menu to get started.</p><button className="primary" onClick={() => { setCheckoutOpen(false); setView('menu') }}>Browse menu</button></div>}</aside></div>}
    {adminOpen && <div className="overlay" role="presentation" onClick={() => setAdminOpen(false)}><aside className="admin-dialog" role="dialog" aria-modal="true" aria-labelledby="admin-title" onClick={(e) => e.stopPropagation()}><button className="icon-button close-dialog" onClick={() => setAdminOpen(false)} aria-label="Close management login"><X /></button><div className="admin-icon"><LockKeyhole /></div><p className="eyebrow">STAFF ACCESS</p><h2 id="admin-title">Management sign in</h2><p>Use your cafeteria manager credentials to open the live queue.</p><div className="checkout-form"><label>Email<input value={adminUser} onChange={(e) => setAdminUser(e.target.value)} placeholder="manager@must.ac.ke" /></label><label>Password<input type="password" value={adminPass} onChange={(e) => setAdminPass(e.target.value)} placeholder="Password" /></label>{adminError && <small className="error-note">{adminError}</small>}<button className="primary" onClick={loginManagement}>Open management</button></div><div className="demo-credentials"><strong>Demo access</strong><span>manager@must.ac.ke</span><span>MUST2026!</span></div></aside></div>}
    <footer><div><img src="/must-icon.svg" alt="MUST logo" /><span>Campus food ordering · Meru University of Science and Technology</span></div><div className="footer-links"><button onClick={() => setView('menu')}>Menu</button><button onClick={() => setView('track')}>Track order</button><button><CircleHelp /> Help</button></div><small>MUST Cafeteria · M-Pesa payments</small></footer>
  </div>
}
