'use client'

import { useEffect, useMemo, useState } from 'react'
import { ArrowRight, Check, ChevronDown, CircleHelp, Clock3, Menu, Moon, Minus, Plus, Search, ShoppingBag, Sun, Ticket, Truck, Utensils, X } from 'lucide-react'

type Meal = { id: string; name: string; description: string; price: number; category: string; type: 'Student Meals' | 'Premium Dining'; image: string; available: boolean }
type CartItem = Meal & { quantity: number }

const meals: Meal[] = [
  { id: 'rice-beans', name: 'Rice + Beans', description: 'Rice served with beans stew', price: 50, category: 'Plates', type: 'Student Meals', image: 'https://images.unsplash.com/photo-1585937421612-70a008356fbe?auto=format&fit=crop&w=800&q=80', available: true },
  { id: 'ugali-beef', name: 'Ugali + Beef', description: 'Ugali with tender beef stew', price: 100, category: 'Plates', type: 'Student Meals', image: 'https://images.unsplash.com/photo-1601050690597-df0568f70950?auto=format&fit=crop&w=800&q=80', available: true },
  { id: 'githeri', name: 'Githeri', description: 'Maize and beans, lightly seasoned', price: 50, category: 'Plates', type: 'Student Meals', image: 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?auto=format&fit=crop&w=800&q=80', available: true },
  { id: 'chapati-beans', name: 'Chapati + Beans', description: 'Soft chapati with beans stew', price: 70, category: 'Plates', type: 'Student Meals', image: 'https://images.unsplash.com/photo-1628294895950-9805252327bc?auto=format&fit=crop&w=800&q=80', available: true },
  { id: 'sukuma', name: 'Sukuma Wiki', description: 'Freshly cooked greens', price: 30, category: 'Sides', type: 'Student Meals', image: 'https://images.unsplash.com/photo-1540420773420-3366772f4999?auto=format&fit=crop&w=800&q=80', available: true },
  { id: 'mandazi', name: 'Mandazi', description: 'Fresh campus breakfast pastry', price: 20, category: 'Breakfast', type: 'Student Meals', image: 'https://images.unsplash.com/photo-1623238913973-21e45cced554?auto=format&fit=crop&w=800&q=80', available: true },
  { id: 'pilau', name: 'Pilau', description: 'Fragrant spiced rice with beef', price: 150, category: 'Plates', type: 'Premium Dining', image: 'https://images.unsplash.com/photo-1599043513900-ed6fe01d4d58?auto=format&fit=crop&w=800&q=80', available: true },
  { id: 'chicken-rice', name: 'Chicken + Rice', description: 'Roast chicken with seasoned rice', price: 220, category: 'Plates', type: 'Premium Dining', image: 'https://images.unsplash.com/photo-1532550907401-a500c9a57435?auto=format&fit=crop&w=800&q=80', available: false },
]

export default function Home() {
  const [section, setSection] = useState<'Student Meals' | 'Premium Dining'>('Student Meals')
  const [category, setCategory] = useState('All')
  const [query, setQuery] = useState('')
  const [cart, setCart] = useState<CartItem[]>([])
  const [view, setView] = useState<'home' | 'menu' | 'track' | 'management'>('home')
  const [checkoutOpen, setCheckoutOpen] = useState(false)
  const [order, setOrder] = useState<{ code: string; name: string; total: number; status: string } | null>(null)
  const [dark, setDark] = useState(false)
  const [mobileNav, setMobileNav] = useState(false)
  const [trackCode, setTrackCode] = useState('')
  const [served, setServed] = useState(false)
  const [name, setName] = useState('')
  const [phone, setPhone] = useState('')

  useEffect(() => {
    if ('serviceWorker' in navigator) navigator.serviceWorker.register('/sw.js').catch(() => undefined)
  }, [])

  const categories = ['All', ...Array.from(new Set(meals.filter((meal) => meal.type === section).map((meal) => meal.category)))]
  const filteredMeals = useMemo(() => meals.filter((meal) => meal.type === section && (category === 'All' || meal.category === category) && `${meal.name} ${meal.description}`.toLowerCase().includes(query.toLowerCase())), [section, category, query])
  const count = cart.reduce((sum, item) => sum + item.quantity, 0)
  const total = cart.reduce((sum, item) => sum + item.price * item.quantity, 0)

  function add(meal: Meal) { if (!meal.available) return; setCart((items) => items.some((item) => item.id === meal.id) ? items.map((item) => item.id === meal.id ? { ...item, quantity: item.quantity + 1 } : item) : [...items, { ...meal, quantity: 1 }]) }
  function change(id: string, delta: number) { setCart((items) => items.map((item) => item.id === id ? { ...item, quantity: item.quantity + delta } : item).filter((item) => item.quantity > 0)) }
  function placeOrder() { if (!name.trim() || phone.length < 9 || !cart.length) return; setOrder({ code: `MUST-${Math.floor(1000 + Math.random() * 9000)}`, name, total, status: 'Payment confirmed' }); setCheckoutOpen(false); setCart([]); setView('track') }

  return <div className={dark ? 'app dark' : 'app'}>
    <header className="site-header"><div className="header-inner">
      <button className="brand" onClick={() => setView('home')} aria-label="MUST Cafeteria home"><img src="https://www.must.ac.ke/wp-content/uploads/2022/07/logo4_png_version.fw_.png" alt="Meru University of Science and Technology" /><span><strong>MUST Cafeteria</strong><small>Campus food ordering</small></span></button>
      <nav className={mobileNav ? 'main-nav open' : 'main-nav'} aria-label="Main navigation"><button className={view === 'home' ? 'active' : ''} onClick={() => { setView('home'); setMobileNav(false) }}>Home</button><button className={view === 'menu' ? 'active' : ''} onClick={() => { setView('menu'); setMobileNav(false) }}>Menu</button><button className={view === 'track' ? 'active' : ''} onClick={() => { setView('track'); setMobileNav(false) }}>Track order</button><button onClick={() => setMobileNav(false)}>Help</button><button className="management-link" onClick={() => { setView('management'); setMobileNav(false) }}>Management</button></nav>
      <div className="header-actions"><button className="icon-button" onClick={() => setDark(!dark)} aria-label={dark ? 'Use light theme' : 'Use dark theme'}>{dark ? <Sun /> : <Moon />}</button><button className="cart-button" onClick={() => setCheckoutOpen(true)} aria-label={`Cart with ${count} items`}><ShoppingBag /><span>{count}</span></button><button className="menu-button" onClick={() => setMobileNav(!mobileNav)} aria-label="Open menu"><Menu /></button></div>
    </div></header>

    <main>
      {view === 'home' && <><section className="service-hero"><div><p className="eyebrow">MERU UNIVERSITY OF SCIENCE AND TECHNOLOGY</p><h1>Order lunch before you reach the counter.</h1><p className="hero-copy">Choose your meal, pay with M-Pesa, and collect it faster from the cafeteria.</p><div className="hero-actions"><button className="primary" onClick={() => setView('menu')}>Order lunch <ArrowRight /></button><button className="text-button" onClick={() => setView('menu')}>View today&apos;s menu</button></div></div><div className="service-note"><span className="live-dot" />Prototype mode · ordering enabled for testing</div></section><section className="service-status"><div><span className="eyebrow">TODAY&apos;S SERVICE</span><h2>Lunch <span className="status-pill">Open</span></h2><p>Available now · Monday to Friday</p></div><div className="section-choice"><button className={section === 'Student Meals' ? 'selected' : ''} onClick={() => { setSection('Student Meals'); setView('menu') }}>Student Meals<span>Affordable everyday plates</span></button><button className={section === 'Premium Dining' ? 'selected' : ''} onClick={() => { setSection('Premium Dining'); setView('menu') }}>Premium Dining<span>More choice for your day</span></button></div></section></>}
      {(view === 'home' || view === 'menu') && <section className="menu-section" id="menu"><div className="section-heading"><div><p className="eyebrow">AVAILABLE TODAY</p><h2>{view === 'home' ? 'Choose your meal' : 'Lunch menu'}</h2></div><button className="outline-button" onClick={() => setView('menu')}>See full menu <ArrowRight /></button></div><div className="menu-toolbar"><div className="segmented"><button className={section === 'Student Meals' ? 'selected' : ''} onClick={() => { setSection('Student Meals'); setCategory('All') }}>Student Meals</button><button className={section === 'Premium Dining' ? 'selected' : ''} onClick={() => { setSection('Premium Dining'); setCategory('All') }}>Premium Dining</button></div><label className="search-box"><Search /><input value={query} onChange={(e) => setQuery(e.target.value)} placeholder="What are you looking for?" aria-label="Search meals" /></label></div><div className="filter-row">{categories.map((item) => <button key={item} className={category === item ? 'filter active' : 'filter'} onClick={() => setCategory(item)}>{item}</button>)}</div><div className="meal-grid">{filteredMeals.map((meal) => <article className="meal-card" key={meal.id}><div className="meal-image"><img src={meal.image} alt={meal.name} loading="lazy" /><span className={meal.available ? 'available' : 'sold-out'}>{meal.available ? 'Available' : 'Sold out'}</span></div><div className="meal-info"><div><h3>{meal.name}</h3><p>{meal.description}</p></div><div className="meal-buy"><strong>KES {meal.price}</strong><button className="add-button" disabled={!meal.available} onClick={() => add(meal)}>{meal.available ? <><Plus /> Add</> : 'Sold out'}</button></div></div></article>)}</div>{!filteredMeals.length && <div className="empty"><Search /><h3>No meals found.</h3><p>Try another search.</p></div>}</section>}
      {view === 'track' && <section className="page-section track-page"><p className="eyebrow">ORDER STATUS</p><h1>Track your order</h1><p className="lead">Enter your order code to see the latest update at the counter.</p><div className="track-form"><input value={trackCode} onChange={(e) => setTrackCode(e.target.value)} placeholder="e.g. MUST-4821" aria-label="Order code" /><button className="primary" onClick={() => setTrackCode(order?.code ?? trackCode)}>Find order</button></div>{order && <div className="order-status"><div className="order-status-top"><div><span className="eyebrow">ORDER {order.code}</span><h2>{order.name}&apos;s lunch</h2></div><span className="status-pill">{served ? 'Served' : order.status}</span></div><div className="progress"><div className="progress-step done"><span><Check /></span><b>Order received</b><small>We have your order</small></div><div className="progress-step done"><span><Check /></span><b>Payment confirmed</b><small>M-Pesa simulation complete</small></div><div className={served ? 'progress-step done' : 'progress-step'}><span>{served ? <Check /> : <Clock3 />}</span><b>{served ? 'Served' : 'Ready for pickup'}</b><small>{served ? 'Enjoy your meal' : 'Say your code at the counter'}</small></div></div><div className="pickup-note"><Ticket /> <span>Go to the cafeteria counter and say <strong>{order.code}</strong>.</span></div></div>}{!order && <div className="track-empty"><Truck /><h3>Your order will appear here.</h3><p>After payment, use the code on your confirmation screen.</p></div>}</section>}
      {view === 'management' && <section className="page-section management-page"><div className="management-head"><div><p className="eyebrow">CAFETERIA OPERATIONS</p><h1>Live order queue</h1><p className="lead">Lunch · Section A · First come, first served</p></div><span className="prototype-badge">Prototype dashboard</span></div><div className="stats"><div><span>Active orders</span><strong>{served ? 0 : order ? 1 : 7}</strong></div><div><span>Today&apos;s revenue</span><strong>KES {order ? order.total + 1240 : '1,240'}</strong></div><div><span>Served</span><strong>{served ? 8 : 7}</strong></div></div><div className="queue"><div className="queue-heading"><h2>Orders to serve</h2><span className="status-pill">Live</span></div>{order && !served ? <div className="queue-row"><div className="queue-number">#8</div><div className="queue-details"><strong>{order.code} · {order.name}</strong><span>Rice + Beans · 1 item · Paid just now</span></div><strong>KES {order.total}</strong><button className="primary small" onClick={() => setServed(true)}>Mark served</button></div> : <div className="queue-empty"><Check /><span>{served ? 'Order served. The queue is clear.' : 'No new demo orders yet.'}</span></div>}</div></section>}
    </main>

    {count > 0 && !checkoutOpen && <button className="sticky-cart" onClick={() => setCheckoutOpen(true)}><span><ShoppingBag /> {count} {count === 1 ? 'item' : 'items'}</span><strong>KES {total} <ArrowRight /></strong></button>}
    {checkoutOpen && <div className="overlay" role="presentation" onClick={() => setCheckoutOpen(false)}><aside className="cart-drawer" role="dialog" aria-modal="true" aria-labelledby="cart-title" onClick={(e) => e.stopPropagation()}><div className="drawer-head"><div><p className="eyebrow">YOUR ORDER</p><h2 id="cart-title">Cart <span>({count})</span></h2></div><button className="icon-button" onClick={() => setCheckoutOpen(false)} aria-label="Close cart"><X /></button></div>{cart.length ? <><div className="cart-items">{cart.map((item) => <div className="cart-item" key={item.id}><img src={item.image} alt="" /><div><strong>{item.name}</strong><span>KES {item.price} each</span><div className="quantity"><button onClick={() => change(item.id, -1)} aria-label={`Remove one ${item.name}`}><Minus /></button><b>{item.quantity}</b><button onClick={() => change(item.id, 1)} aria-label={`Add one ${item.name}`}><Plus /></button></div></div><strong>KES {item.price * item.quantity}</strong></div>)}</div><div className="cart-total"><span>Total</span><strong>KES {total}</strong></div><div className="checkout-form"><label>Full name<input value={name} onChange={(e) => setName(e.target.value)} placeholder="e.g. John Mwangi" /></label><label>Phone number<input value={phone} onChange={(e) => setPhone(e.target.value)} placeholder="07XX XXX XXX" inputMode="tel" /></label><button className="primary pay-button" disabled={!name.trim() || phone.length < 9} onClick={placeOrder}>Pay KES {total} with M-Pesa <ArrowRight /></button><small className="secure-note">Prototype payment · No real money will be charged</small></div></> : <div className="cart-empty"><ShoppingBag /><h3>Your cart is empty</h3><p>Add a meal from today&apos;s menu to get started.</p><button className="primary" onClick={() => { setCheckoutOpen(false); setView('menu') }}>Browse menu</button></div>}</aside></div>}
    <footer><div><strong>MUST Cafeteria</strong><span>Meru University of Science and Technology</span></div><div className="footer-links"><button onClick={() => setView('menu')}>Menu</button><button onClick={() => setView('track')}>Track order</button><button><CircleHelp /> Help</button></div><small>Prototype mode · Campus food ordering</small></footer>
  </div>
}
